cd C:\mywork\seleniumgit\munivisorautomatedtestSelenium\testAutomationAnywhere\seleniumGrid\setup\bat
start hubStart.bat
start loadnode1Chrome.bat
start loadnode2Chrome.bat
start loadnode3Chrome.bat
start loadnode4Chrome.bat
start loadnode5Chrome.bat
start loadnode6Chrome.bat
start loadnode7Chrome.bat
start loadnode8Chrome.bat
start loadnode9Chrome.bat
start loadnode10Chrome.bat