cd C:\mywork\seleniumgit\munivisorautomatedtestSelenium\testAutomationAnywhere\seleniumGrid\setup\bat
start hubStart.bat
start loadnode1Chrome.bat
start loadnode2Chrome.bat
start loadnode3Chrome.bat
start loadnode4Chrome.bat
start loadnode5Chrome.bat
start loadnodenode11IEedge.bat
start loadnodenode12IEedge.bat
start loadnodenode13IEedge.bat
start loadnodenode14IEedge.bat
start loadnodenode15IEedge.bat